services:

  db:
    image: postgres:latest
    container_name: chatbot_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5432
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot_db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: postgres -p 5432

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_back
    command: sh -c "uvicorn app:app --reload --host 0.0.0.0 --port 8006"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports: 
      - "8006:8006"
    depends_on:
      - db
          
    volumes:
      - .:/app
    networks:
      - chatbot_db-net
      - chatbot_web-net
    env_file:
      - .env


volumes:
  postgres_data:
  # static_volume:
networks:
  chatbot_db-net:
  chatbot_web-net: