"""User: add refresh_token column

Revision ID: 86223789edb9
Revises: 982c062f1a0c
Create Date: 2025-03-25 11:09:48.397980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86223789edb9'
down_revision: Union[str, None] = '982c062f1a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
